name: malaria_prediction_app
description: AI-powered malaria outbreak prediction and monitoring application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  equatable: ^2.0.5
  
  # Networking & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  web_socket_channel: ^2.4.0
  connectivity_plus: ^5.0.1
  pretty_dio_logger: ^1.3.1
  
  # Maps & Geospatial
  flutter_map: ^6.0.1
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Data Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # UI & Animation
  fl_chart: ^0.64.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  
  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.6
  crypto: ^3.0.3
  
  # Navigation
  go_router: ^12.1.3
  
  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.2
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700