# Comprehensive Flutter Analysis Configuration for Malaria Prediction App
# Enforces strict code quality standards for multi-agent development
# Based on enterprise-grade Flutter best practices

include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"
    - "**/generated_plugin_registrant.dart"

  errors:
    # Treat certain warnings as errors for strict quality control
    missing_required_param: error
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error
    todo: ignore # Allow TODO comments for development

linter:
  rules:
    # Error Prevention Rules
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_brace_in_string_interps: true

    # Code Quality Rules
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    await_only_futures: true

    # Naming Conventions
    camel_case_extensions: true
    camel_case_types: true
    constant_identifier_names: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true

    # Documentation
    public_member_api_docs: false # Enable for production
    package_api_docs: false # Enable for production

    # Style Guidelines
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    library_private_types_in_public_api: true
    no_duplicate_case_values: true
    null_closures: true
    overridden_fields: true
    package_names: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true

    # Security & Performance
    avoid_catching_errors: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    diagnostic_describe_all_properties: false # Enable for production

    # Flutter Specific
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true

    # Testing
    avoid_final_parameters: false
    prefer_const_parameters: false
